# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Repack a released wheel with pure-Python changes from a descendant commit."""

from __future__ import annotations

import argparse
import binascii
import csv
import hashlib
import io
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path, PurePosixPath


class OverlayError(RuntimeError):
    """The requested wheel overlay is unsafe or malformed."""


def _changed_package_paths(
    repository: Path, base_commit: str, head_commit: str
) -> list[tuple[str, str]]:
    ancestry = subprocess.run(
        ["git", "merge-base", "--is-ancestor", base_commit, head_commit],
        cwd=repository,
        check=False,
    )
    if ancestry.returncode == 1:
        raise OverlayError(
            f"overlay head {head_commit} is not a descendant of base {base_commit}"
        )
    ancestry.check_returncode()
    completed = subprocess.run(
        [
            "git",
            "diff",
            "--name-status",
            "--no-renames",
            f"{base_commit}..{head_commit}",
            "--",
            "vllm",
        ],
        cwd=repository,
        check=True,
        capture_output=True,
        text=True,
    )
    changes: list[tuple[str, str]] = []
    for line in completed.stdout.splitlines():
        status, relative_path = line.split("\t", 1)
        if status not in {"A", "M", "D"}:
            raise OverlayError(
                f"unsupported package change status {status!r}: {relative_path}"
            )
        path = PurePosixPath(relative_path)
        if path.is_absolute() or ".." in path.parts or path.suffix != ".py":
            raise OverlayError(
                "binary wheel overlays may change only vllm Python files: "
                f"{relative_path}"
            )
        changes.append((status, relative_path))
    if not changes:
        raise OverlayError("the selected commits contain no vllm Python changes")
    return changes


def _safe_extract(wheel: Path, destination: Path) -> None:
    with zipfile.ZipFile(wheel) as archive:
        unsafe = [
            name
            for name in archive.namelist()
            if PurePosixPath(name).is_absolute() or ".." in PurePosixPath(name).parts
        ]
        if unsafe:
            raise OverlayError(f"wheel contains unsafe paths: {unsafe[:3]}")
        archive.extractall(destination)


def _replace_metadata_version(metadata_path: Path, version: str) -> None:
    lines = metadata_path.read_text().splitlines(keepends=True)
    version_lines = [
        index for index, line in enumerate(lines) if line.startswith("Version: ")
    ]
    if len(version_lines) != 1:
        raise OverlayError(
            f"expected one Version field in {metadata_path}, found {len(version_lines)}"
        )
    index = version_lines[0]
    newline = "\n" if lines[index].endswith("\n") else ""
    lines[index] = f"Version: {version}{newline}"
    metadata_path.write_text("".join(lines))


def _write_runtime_version(package_root: Path, version: str) -> None:
    (package_root / "_version.py").write_text(
        "# Generated by infra/release/python_overlay_wheel.py\n"
        "__all__ = [\"__version__\", \"__version_tuple__\", \"version\", "
        "\"version_tuple\", \"__commit_id__\", \"commit_id\"]\n"
        f"__version__ = version = {version!r}\n"
        "__version_tuple__ = version_tuple = (0, 0, 0, __version__)\n"
        "__commit_id__ = commit_id = None\n"
    )


def _record_row(path: Path, root: Path) -> tuple[str, str, str]:
    contents = path.read_bytes()
    digest = (
        binascii.b2a_base64(hashlib.sha256(contents).digest(), newline=False)
        .rstrip(b"=")
        .translate(bytes.maketrans(b"+/", b"-_"))
        .decode()
    )
    return path.relative_to(root).as_posix(), f"sha256={digest}", str(len(contents))


def _rewrite_record(root: Path, dist_info: Path) -> None:
    record_path = dist_info / "RECORD"
    rows = [
        _record_row(path, root)
        for path in sorted(root.rglob("*"))
        if path.is_file() and path != record_path
    ]
    rows.append((record_path.relative_to(root).as_posix(), "", ""))
    output = io.StringIO(newline="")
    csv.writer(output, lineterminator="\n").writerows(rows)
    record_path.write_text(output.getvalue())


def repack_python_overlay(
    *,
    base_wheel: Path,
    repository: Path,
    base_commit: str,
    head_commit: str,
    version: str,
    output_dir: Path,
) -> Path:
    """Overlay pure-Python package changes while preserving every compiled artifact."""
    if (
        not version
        or not version[0].isalnum()
        or any(not (character.isalnum() or character in ".+_") for character in version)
    ):
        raise OverlayError(f"invalid wheel version {version!r}")
    changes = _changed_package_paths(repository, base_commit, head_commit)
    wheel_stem = base_wheel.name.removesuffix(".whl")
    filename_parts = wheel_stem.rsplit("-", 3)
    if len(filename_parts) != 4 or not filename_parts[0].startswith("vllm-"):
        raise OverlayError(f"cannot parse vllm wheel filename: {base_wheel.name}")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_wheel = output_dir / f"vllm-{version}-{'-'.join(filename_parts[1:])}.whl"

    with tempfile.TemporaryDirectory(prefix="marin-vllm-python-overlay-") as temporary:
        root = Path(temporary)
        _safe_extract(base_wheel, root)
        dist_infos = list(root.glob("vllm-*.dist-info"))
        if len(dist_infos) != 1:
            raise OverlayError(
                f"expected one vllm dist-info directory, found {len(dist_infos)}"
            )
        old_dist_info = dist_infos[0]
        dist_info = root / f"vllm-{version}.dist-info"
        old_dist_info.rename(dist_info)

        for status, relative_path in changes:
            source = repository / relative_path
            destination = root / relative_path
            if status == "D":
                destination.unlink(missing_ok=True)
                continue
            if not source.is_file():
                raise OverlayError(f"overlay source does not exist: {source}")
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)

        _replace_metadata_version(dist_info / "METADATA", version)
        _write_runtime_version(root / "vllm", version)
        _rewrite_record(root, dist_info)
        with zipfile.ZipFile(
            output_wheel, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6
        ) as archive:
            for path in sorted(root.rglob("*")):
                if path.is_file():
                    archive.write(path, path.relative_to(root).as_posix())
    return output_wheel


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-wheel", type=Path, required=True)
    parser.add_argument("--repository", type=Path, default=Path.cwd())
    parser.add_argument("--base-commit", required=True)
    parser.add_argument("--head-commit", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    output = repack_python_overlay(
        base_wheel=args.base_wheel,
        repository=args.repository,
        base_commit=args.base_commit,
        head_commit=args.head_commit,
        version=args.version,
        output_dir=args.output_dir,
    )
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
